// /cursors/index.js
// Centralized list of all cursors, sorted alphabetically by name.

export const CURSORS = [
  { id: "none", name: "Default", file: null },

  { id: "ak47", name: "AK-47", file: "cursors/ak47.png", hotspot: "8 8" },
  {
    id: "avenger",
    name: "Avenger",
    file: "cursors/avenger.png",
    hotspot: "8 8",
  },
  { id: "bat", name: "Bat", file: "cursors/bat.png", hotspot: "8 8" },
  { id: "bolt", name: "Bolt", file: "cursors/bolt.png", hotspot: "8 8" },
  {
    id: "caption_america",
    name: "Captain America",
    file: "cursors/caption_america.png",
    hotspot: "8 8",
  },
  { id: "circle", name: "Circle", file: "cursors/circle.png", hotspot: "8 8" },
  {
    id: "classic",
    name: "Classic Arrow",
    file: "cursors/classic-arrow.png",
    hotspot: "0 0",
  },
  { id: "click", name: "Click", file: "cursors/click.png", hotspot: "8 8" },
  {
    id: "click2",
    name: "Click 2",
    file: "cursors/click-2.png",
    hotspot: "8 8",
  },
  {
    id: "click3",
    name: "Click 3",
    file: "cursors/click-3.png",
    hotspot: "8 8",
  },
  {
    id: "computer",
    name: "Computer",
    file: "cursors/computer.png",
    hotspot: "8 8",
  },
  {
    id: "cursor_fill",
    name: "Cursor Fill",
    file: "cursors/cursor_fill.png",
    hotspot: "8 8",
  },
  {
    id: "cursor_mashroom",
    name: "Cursor Mushroom",
    file: "cursors/cursor_mashroom.png",
    hotspot: "8 8",
  },
  {
    id: "cursor_pink",
    name: "Cursor Pink",
    file: "cursors/cursor_pink.png",
    hotspot: "8 8",
  },
  {
    id: "cursor_rounds",
    name: "Cursor Rounds",
    file: "cursors/cursor_rounds.png",
    hotspot: "8 8",
  },
  { id: "delete", name: "Delete", file: "cursors/delete.png", hotspot: "8 8" },
  {
    id: "gradient",
    name: "Gradient",
    file: "cursors/gradient.png",
    hotspot: "8 8",
  },
  { id: "hand", name: "Hand", file: "cursors/hand.png", hotspot: "8 8" },
  {
    id: "iron_man",
    name: "Iron Man",
    file: "cursors/iron_man.png",
    hotspot: "8 8",
  },
  { id: "kawaii", name: "Kawaii", file: "cursors/kawaii.png", hotspot: "8 8" },
  {
    id: "left_click",
    name: "Left Click",
    file: "cursors/left-click.png",
    hotspot: "8 8",
  },
  { id: "logan", name: "Logan", file: "cursors/logan.png", hotspot: "8 8" },
  { id: "love", name: "Love", file: "cursors/love.png", hotspot: "8 8" },
  { id: "magic", name: "Magic", file: "cursors/magic.png", hotspot: "8 8" },
  {
    id: "middle_finger",
    name: "Middle Finger",
    file: "cursors/middle_finger.png",
    hotspot: "8 8",
  },
  {
    id: "navigation",
    name: "Navigation",
    file: "cursors/navigation.png",
    hotspot: "8 8",
  },
  { id: "pen", name: "Pen", file: "cursors/pen.png", hotspot: "8 8" },
  {
    id: "pointer",
    name: "Pointer",
    file: "cursors/pointer.png",
    hotspot: "8 8",
  },
  {
    id: "pointer_start",
    name: "Pointer Start",
    file: "cursors/pointer_start.png",
    hotspot: "8 8",
  },
  {
    id: "precision",
    name: "Precision",
    file: "cursors/precision.png",
    hotspot: "8 8",
  },
  { id: "reload", name: "Reload", file: "cursors/reload.png", hotspot: "8 8" },
  { id: "rocket", name: "Rocket", file: "cursors/rocket.png", hotspot: "8 8" },
  {
    id: "selection",
    name: "Selection",
    file: "cursors/selection.png",
    hotspot: "8 8",
  },
  { id: "shield", name: "Shield", file: "cursors/shield.png", hotspot: "8 8" },
  {
    id: "spiderman",
    name: "Spiderman",
    file: "cursors/spiderman.png",
    hotspot: "8 8",
  },
  {
    id: "superman",
    name: "Superman",
    file: "cursors/superman.png",
    hotspot: "8 8",
  },
  {
    id: "superman2",
    name: "Superman 2",
    file: "cursors/superman-2.png",
    hotspot: "8 8",
  },
  { id: "sword", name: "Sword", file: "cursors/sword.png", hotspot: "8 8" },
  { id: "target", name: "Target", file: "cursors/target.png", hotspot: "8 8" },
  { id: "text", name: "Text", file: "cursors/text.png", hotspot: "8 8" },
  { id: "tool", name: "Tool", file: "cursors/tools.png", hotspot: "8 8" },
];
// Note: Hotspot coordinates are optional; if not provided, the browser defaults will be used.
